<?php

namespace VRPlayAdminBundle\Entity;

/**
 * AppVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
