<?php

namespace VRPlayAdminBundle\Entity;

/**
 * UserFlaggedCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFlaggedCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
