<?php

namespace VRPlayAdminBundle\Entity;

/**
 * UserFlaggedAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFlaggedAppRepository extends \Doctrine\ORM\EntityRepository
{
}
