vr_play_admin_category:
    resource: "@VRPlayAdminBundle/Controller/CategoryController.php"
    type:     annotation

vr_play_admin_genre:
    resource: "@VRPlayAdminBundle/Controller/GenreController.php"
    type:     annotation

vr_play_admin_genre:
    resource: "@VRPlayAdminBundle/Controller/GenreController.php"
    type:     annotation

vr_custom_user:
    resource: "@VRCustomUserBundle/Controller/"
    type:     annotation
    prefix:   /

vr_play_audit:
    resource: "@VRPlayAuditBundle/Controller/"
    type:     annotation
    prefix:   /logs

vr_play:
    resource: "@VRPlayBundle/Controller/"
    type:     annotation
    prefix:   /

vr_play_admin:
    resource: "@VRPlayAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"